name: cronolab
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 3.0.1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  bot_toast: ^4.0.3
  cloud_firestore: ^4.1.0
  cupertino_icons: ^1.0.2
  custom_refresh_indicator: ^1.2.1
  firebase_auth: ^4.1.4
  firebase_core: ^2.3.0
  firebase_analytics: ^10.3.0
  firedart: ^0.9.0+1
  flutter:
    sdk: flutter
  
  google_sign_in: ^5.4.1
  http: ^0.13.4
  internet_connection_checker: ^0.0.1+4
  liquid_pull_to_refresh: ^3.0.1
  onesignal_flutter: ^3.0.0
  open_file: ^3.2.1
  path: ^1.8.1
  path_provider: any
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  sqflite: ^2.0.3
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Bold.ttf
        - asset: assets/fonts/inter/Inter-Medium.ttf
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
        - asset: assets/fonts/inter/Inter-Regular.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
